### ISSUE TITLE
[BUG] - links don't work in the pdf lmao

### ISSUE THREAD

**Issue by DJshelfmushroom** [theshmunguss1/RamHub#8]
**Describe the bug**
title

**To Reproduce**
look at the doc and try to click on a link

**Expected behavior**
opens website

**Comment by DJshelfmushroom** [comment]
i might be able to solve this if you can send me a copy of the doc, but I'm not sure if RPS will let you do that.

**Comment by Keduffy** [comment]
right click --> open in new tab

**Comment by DJshelfmushroom** [comment]
I see no option to open in new tab, explain in more detail @Keduffy?

**Comment by DJshelfmushroom** [comment]
However downloading and then clicking does work.

**Comment by DJshelfmushroom** [comment]
> right click on one of the links

@Keduffy 
[Screen recording 2024-04-05 8.00.33 AM.webm](https://github.com/theshmunguss1/RamHub/assets/67295452/48d9f327-e67f-4255-b711-5ee13d5b159f)
